export interface SegmentData {
  id: number;
  start: number;
  end: number;
  text: string;
}

function formatTime(sec: number): string {
  const m = Math.floor(sec / 60);
  const s = Math.floor(sec % 60);
  return `${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
}

export function downloadFile(filename: string, content: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportAsMarkdown(title: string, transcript: string, segments: SegmentData[] = []) {
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  let md = `# ${title} — Transcript\n\n`;
  md += `> **Date:** ${dateStr}  \n`;
  md += `> **Word Count:** ${transcript.split(/\\s+/).filter(Boolean).length} words  \n`;
  md += `> **Platform:** Sonic AI Studio\n\n`;
  md += `---\n\n`;
  md += `## Clean Reading Transcript\n\n`;
  md += `${transcript}\n\n`;

  if (segments.length > 0) {
    md += `---\n\n`;
    md += `## Timecoded Segments\n\n`;
    md += `| Timecode | Text |\n`;
    md += `| :--- | :--- |\n`;
    segments.forEach((seg) => {
      md += `| \`${formatTime(seg.start)} → ${formatTime(seg.end)}\` | ${seg.text.replace(/\|/g, '\\|')} |\n`;
    });
    md += `\n`;
  }

  const safeFilename = `${title.toLowerCase().replace(/[^a-z0-9]+/g, '_')}_transcript.md`;
  downloadFile(safeFilename, md, 'text/markdown;charset=utf-8');
}

export function exportAsTxt(title: string, transcript: string) {
  const safeFilename = `${title.toLowerCase().replace(/[^a-z0-9]+/g, '_')}_transcript.txt`;
  downloadFile(safeFilename, transcript, 'text/plain;charset=utf-8');
}

export function exportAsDoc(title: string, transcript: string, segments: SegmentData[] = []) {
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  let htmlContent = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head>
      <meta charset='utf-8'>
      <title>${title} Transcript</title>
      <style>
        body { font-family: 'Segoe UI', Calibri, Arial, sans-serif; line-height: 1.8; color: #111; margin: 40px; }
        h1 { color: #008060; border-bottom: 2px solid #008060; padding-bottom: 8px; font-size: 22px; }
        .meta { color: #666; font-size: 12px; margin-bottom: 24px; }
        .transcript-text { font-size: 14px; line-height: 1.8; margin-bottom: 30px; white-space: pre-wrap; }
        table { border-collapse: collapse; width: 100%; font-size: 13px; margin-top: 16px; }
        th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
        th { background-color: #f5f5f5; font-weight: bold; }
        .timecode { font-family: monospace; color: #008060; font-weight: bold; white-space: nowrap; }
      </style>
    </head>
    <body>
      <h1>${title}</h1>
      <div class='meta'>
        <strong>Date:</strong> ${dateStr} &bull; 
        <strong>Word Count:</strong> ${transcript.split(/\\s+/).filter(Boolean).length} words &bull; 
        <strong>Generated by:</strong> Sonic AI
      </div>

      <h3 style="color: #333;">Continuous Transcript</h3>
      <div class='transcript-text'>${transcript.replace(/\n/g, '<br/><br/>')}</div>
  `;

  if (segments.length > 0) {
    htmlContent += `
      <h3 style="color: #333; margin-top: 32px;">Timestamped Breakdown</h3>
      <table>
        <thead>
          <tr>
            <th style='width: 140px;'>Timecode</th>
            <th>Transcript Text</th>
          </tr>
        </thead>
        <tbody>
    `;
    segments.forEach((seg) => {
      htmlContent += `
        <tr>
          <td class='timecode'>[${formatTime(seg.start)} - ${formatTime(seg.end)}]</td>
          <td>${seg.text}</td>
        </tr>
      `;
    });
    htmlContent += `
        </tbody>
      </table>
    `;
  }

  htmlContent += `
    </body>
    </html>
  `;

  const safeFilename = `${title.toLowerCase().replace(/[^a-z0-9]+/g, '_')}_transcript.doc`;
  downloadFile(safeFilename, htmlContent, 'application/msword;charset=utf-8');
}

export function exportAsPdf(title: string, transcript: string, segments: SegmentData[] = []) {
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to export to PDF.');
    return;
  }

  let segmentRows = '';
  segments.forEach((seg) => {
    segmentRows += `
      <div style="display: flex; gap: 16px; margin-bottom: 10px; font-size: 13px; line-height: 1.5;">
        <span style="font-family: monospace; font-weight: bold; color: #008060; width: 110px; flex-shrink: 0;">
          [${formatTime(seg.start)} → ${formatTime(seg.end)}]
        </span>
        <span style="color: #222;">${seg.text}</span>
      </div>
    `;
  });

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title} — Transcript</title>
        <style>
          @page { margin: 20mm; size: A4; }
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #111; line-height: 1.7; padding: 20px; }
          .header { border-bottom: 2px solid #00D4B4; padding-bottom: 12px; margin-bottom: 24px; }
          h1 { margin: 0 0 6px 0; font-size: 22px; color: #0D0D0D; }
          .meta { font-size: 12px; color: #666; }
          .clean-text { font-size: 14px; line-height: 1.8; color: #222; margin-bottom: 36px; white-space: pre-wrap; }
          h2 { font-size: 16px; margin-top: 30px; margin-bottom: 14px; border-bottom: 1px solid #eee; padding-bottom: 6px; }
          @media print {
            body { padding: 0; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${title}</h1>
          <div class="meta">
            <span>Date: ${dateStr}</span> &bull;
            <span>Word Count: ${transcript.split(/\\s+/).filter(Boolean).length}</span> &bull;
            <span>Source: Sonic AI Creator Studio</span>
          </div>
        </div>

        <h2>Transcript</h2>
        <div class="clean-text">${transcript}</div>

        ${
          segments.length > 0
            ? `
          <h2>Timecoded Subtitle Timeline</h2>
          <div>${segmentRows}</div>
        `
            : ''
        }

        <script>
          window.onload = function() {
            window.focus();
            window.print();
          };
        </script>
      </body>
    </html>
  `);

  printWindow.document.close();
}
